// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:1.0.0.0
//      Reqnroll Generator Version:1.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace EtwIngest.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "1.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class EvtxParserFeature
    {
        
        private static Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "EvtxParser.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, System.Threading.Thread.CurrentThread.ManagedThreadId.ToString());
            Reqnroll.FeatureInfo featureInfo = new Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "EvtxParser", "  As a user,\n  I want to be able to parse an EVTX file,\n  So that I can ingest th" +
                    "em into kusto", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "EvtxParser")))
            {
                await global::EtwIngest.Features.EvtxParserFeature.FeatureSetupAsync(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
    await testRunner.GivenAsync("kusto cluster uri \"http://172.20.102.248:8080\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
    await testRunner.AndAsync("kusto database name \"hci\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
#line 9
    await testRunner.AndAsync("kustainer volume mount from \"E:\\\\kustodata\" to \"/kustodata\"", ((string)(null)), ((Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("parse evtx file")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EvtxParser")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("evtx")]
        public async System.Threading.Tasks.Task ParseEvtxFile()
        {
            string[] tagsOfScenario = new string[] {
                    "evtx"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("parse evtx file", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 12
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 13
 await testRunner.GivenAsync("a evtx file at \"%HOME%\\Downloads\\hci\\evtx\\Event_Microsoft.AzureStack.LCMControlle" +
                        "r.EventSource-Admin.EVTX\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 14
 await testRunner.WhenAsync("I parse evtx file", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
                Reqnroll.Table table11 = new Reqnroll.Table(new string[] {
                            "TimeStamp",
                            "Level",
                            "EventId",
                            "LogName",
                            "Description"});
                table11.AddRow(new string[] {
                            "10/8/2024 11:24:22 PM",
                            "Information",
                            "1",
                            "Microsoft.AzureStack.LCMController.EventSource/Admin",
                            "The request is not supported."});
#line 15
 await testRunner.ThenAsync("I should get 4475 evtx records", ((string)(null)), table11, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("parse multiple evtx files")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EvtxParser")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("evtx")]
        public async System.Threading.Tasks.Task ParseMultipleEvtxFiles()
        {
            string[] tagsOfScenario = new string[] {
                    "evtx"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("parse multiple evtx files", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 20
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 21
  await testRunner.GivenAsync("A zip file at \"%HOME%\\\\Downloads\\\\hci.zip\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 22
  await testRunner.WhenAsync("I extract \"evtx\" files from zip file to folder \"%HOME%\\\\Downloads\\\\hci\\\\evtx\"", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
                Reqnroll.Table table12 = new Reqnroll.Table(new string[] {
                            "FileName"});
                table12.AddRow(new string[] {
                            "Event_Microsoft.AzureStack.LCMController.EventSource-Admin.evtx"});
                table12.AddRow(new string[] {
                            "Event_Microsoft-Windows-WinRM-Operational.evtx"});
                table12.AddRow(new string[] {
                            "Event_Microsoft-Windows-WMI-Activity-Operational.evtx"});
#line 23
  await testRunner.ThenAsync("I should see the following \"evtx\" files in folder \"%HOME%\\\\Downloads\\\\hci\\\\evtx\"", ((string)(null)), table12, "Then ");
#line hidden
#line 28
  await testRunner.WhenAsync("I parse evtx files in folder \"%HOME%\\\\Downloads\\\\hci\\\\evtx\"", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
#line 29
  await testRunner.ThenAsync("I should find 4475 distinct records in evtx files", ((string)(null)), ((Reqnroll.Table)(null)), "Then ");
#line hidden
#line 30
  await testRunner.WhenAsync("I create table based on evtx record schema", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
                Reqnroll.Table table13 = new Reqnroll.Table(new string[] {
                            "TableName"});
                table13.AddRow(new string[] {
                            "WindowsEvents"});
#line 31
  await testRunner.ThenAsync("I should see following evtx kusto table", ((string)(null)), table13, "Then ");
#line hidden
                Reqnroll.Table table14 = new Reqnroll.Table(new string[] {
                            "ColumnName",
                            "DataType"});
                table14.AddRow(new string[] {
                            "TimeStamp",
                            "datetime"});
                table14.AddRow(new string[] {
                            "ProviderName",
                            "string"});
                table14.AddRow(new string[] {
                            "LogName",
                            "string"});
                table14.AddRow(new string[] {
                            "MachineName",
                            "string"});
                table14.AddRow(new string[] {
                            "EventId",
                            "int"});
                table14.AddRow(new string[] {
                            "Level",
                            "string"});
                table14.AddRow(new string[] {
                            "Opcode",
                            "dynamic"});
                table14.AddRow(new string[] {
                            "Keywords",
                            "string"});
                table14.AddRow(new string[] {
                            "ProcessId",
                            "dynamic"});
                table14.AddRow(new string[] {
                            "Description",
                            "string"});
#line 34
  await testRunner.AndAsync("kusto table \"WindowsEvents\" should have the following columns", ((string)(null)), table14, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("parse evtx file into csv files")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EvtxParser")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("evtx")]
        public async System.Threading.Tasks.Task ParseEvtxFileIntoCsvFiles()
        {
            string[] tagsOfScenario = new string[] {
                    "evtx"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            Reqnroll.ScenarioInfo scenarioInfo = new Reqnroll.ScenarioInfo("parse evtx file into csv files", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 48
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 49
  await testRunner.GivenAsync("a evtx file at \"%HOME%\\Downloads\\hci\\evtx\\Event_Microsoft.AzureStack.LCMControlle" +
                        "r.EventSource-Admin.EVTX\"", ((string)(null)), ((Reqnroll.Table)(null)), "Given ");
#line hidden
#line 50
  await testRunner.WhenAsync("I ingest evtx file to kusto", ((string)(null)), ((Reqnroll.Table)(null)), "When ");
#line hidden
                Reqnroll.Table table15 = new Reqnroll.Table(new string[] {
                            "TableName",
                            "RecordCount"});
                table15.AddRow(new string[] {
                            "WindowsEvents",
                            "1"});
#line 51
  await testRunner.ThenAsync("the following kusto tables should have added records with expected counts", ((string)(null)), table15, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
