// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ExecutionEngine.IntegrationTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class AdvancedFeaturesFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Advanced Features", "  As a workflow designer\r\n  I want to use advanced node types and capabilities\r\n " +
                " So that I can build complex workflow patterns", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "AdvancedFeatures.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/AdvancedFeatures.feature.ndjson", 23);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Container node execution")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Container node execution")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Advanced Features")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("integration")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("smoke")]
        public async global::System.Threading.Tasks.Task ContainerNodeExecution()
        {
            string[] tagsOfScenario = new string[] {
                    "integration",
                    "smoke"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Container node execution", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 7
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await testRunner.GivenAsync("I have a Container node \"MainContainer\" with child nodes \"Child1\", \"Child2\", \"Chi" +
                        "ld3\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 9
    await testRunner.AndAsync("\"Child1\" connects to \"Child2\" on Complete", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 10
    await testRunner.AndAsync("\"Child2\" connects to \"Child3\" on Complete", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 11
    await testRunner.WhenAsync("I start the workflow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 12
    await testRunner.ThenAsync("the container should start all entry point children", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 13
    await testRunner.AndAsync("\"Child1\", \"Child2\", \"Child3\" should execute in order", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
    await testRunner.AndAsync("the container should complete when all children are done", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
    await testRunner.AndAsync("container output should contain ChildResults with all child data", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
    await testRunner.AndAsync("the workflow should complete successfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Container completes when all children complete")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Container completes when all children complete")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Advanced Features")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task ContainerCompletesWhenAllChildrenComplete()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Container completes when all children complete", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 19
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 20
    await testRunner.GivenAsync("I have a Container with 5 parallel child nodes", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 21
    await testRunner.WhenAsync("I start the workflow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 22
    await testRunner.ThenAsync("the container should wait for all children to complete", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 23
    await testRunner.AndAsync("the container status should be \"Running\" while children execute", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
    await testRunner.AndAsync("the container should complete after the last child completes", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 25
    await testRunner.AndAsync("ChildResults should contain results from all 5 children", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Container fails if any child fails")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Container fails if any child fails")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Advanced Features")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("integration")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("errorhandling")]
        public async global::System.Threading.Tasks.Task ContainerFailsIfAnyChildFails()
        {
            string[] tagsOfScenario = new string[] {
                    "integration",
                    "errorhandling"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Container fails if any child fails", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 28
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 29
    await testRunner.GivenAsync("I have a Container with child nodes \"A\", \"B\", \"C\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 30
    await testRunner.AndAsync("\"B\" is configured to fail", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 31
    await testRunner.WhenAsync("I start the workflow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 32
    await testRunner.ThenAsync("\"B\" should fail", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 33
    await testRunner.AndAsync("the container should fail when \"B\" fails", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
    await testRunner.AndAsync("the container error should indicate child failure", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 35
    await testRunner.AndAsync("remaining children may or may not complete based on error strategy", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Subflow workflow execution")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Subflow workflow execution")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Advanced Features")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task SubflowWorkflowExecution()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Subflow workflow execution", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 38
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 39
    await testRunner.GivenAsync("I have a Subflow node \"CallExternal\" referencing \"ExternalWorkflow.yaml\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "ParentVariable",
                            "SubflowInput"});
                table1.AddRow(new string[] {
                            "userName",
                            "user"});
                table1.AddRow(new string[] {
                            "itemId",
                            "id"});
#line 40
    await testRunner.AndAsync("the subflow has input mappings:", ((string)(null)), table1, "And ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "SubflowOutput",
                            "ParentVariable"});
                table2.AddRow(new string[] {
                            "result",
                            "subflowResult"});
                table2.AddRow(new string[] {
                            "status",
                            "subflowStatus"});
#line 44
    await testRunner.AndAsync("the subflow has output mappings:", ((string)(null)), table2, "And ");
#line hidden
#line 48
    await testRunner.WhenAsync("I start the workflow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 49
    await testRunner.ThenAsync("the external workflow should load from \"ExternalWorkflow.yaml\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 50
    await testRunner.AndAsync("subflow should receive mapped inputs", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 51
    await testRunner.AndAsync("the subflow should execute to completion", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 52
    await testRunner.AndAsync("subflow outputs should be mapped back to parent variables", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 53
    await testRunner.AndAsync("parent workflow should continue after subflow completes", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Nested subflow execution")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Nested subflow execution")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Advanced Features")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task NestedSubflowExecution()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Nested subflow execution", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 56
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 57
    await testRunner.GivenAsync("I have workflow A calling subflow B", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 58
    await testRunner.AndAsync("subflow B calls subflow C", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 59
    await testRunner.AndAsync("subflow C calls subflow D", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 60
    await testRunner.WhenAsync("I start workflow A", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 61
    await testRunner.ThenAsync("all subflows should execute in order: A → B → C → D", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 62
    await testRunner.AndAsync("each subflow should complete successfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 63
    await testRunner.AndAsync("control should return through the chain: D → C → B → A", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 64
    await testRunner.AndAsync("the final workflow should complete successfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Subflow execution with failure handling")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Subflow execution with failure handling")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Advanced Features")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task SubflowExecutionWithFailureHandling()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Subflow execution with failure handling", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 67
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 68
    await testRunner.GivenAsync("I have a Subflow node \"Subflow1\" that references a failing workflow", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 69
    await testRunner.AndAsync("\"Subflow1\" connects to \"HandleError\" on Fail", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 70
    await testRunner.WhenAsync("I start the workflow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 71
    await testRunner.ThenAsync("the subflow should fail", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 72
    await testRunner.AndAsync("the Subflow node should capture the failure", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 73
    await testRunner.AndAsync("\"HandleError\" should execute", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 74
    await testRunner.AndAsync("the parent workflow should handle the subflow failure gracefully", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Timer scheduled trigger")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Timer scheduled trigger")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Advanced Features")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task TimerScheduledTrigger()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Timer scheduled trigger", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 77
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 78
    await testRunner.GivenAsync("I have a Timer node \"ScheduledTask\" with cron expression \"0 0 * * *\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 79
    await testRunner.AndAsync("TriggerOnStart is set to true", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 80
    await testRunner.WhenAsync("I start the workflow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 81
    await testRunner.ThenAsync("the timer should trigger immediately (because of TriggerOnStart)", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 82
    await testRunner.AndAsync("the output should contain Triggered = true", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 83
    await testRunner.AndAsync("downstream nodes should receive the trigger", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 84
    await testRunner.AndAsync("the workflow should complete successfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Timer with condition-based routing")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Timer with condition-based routing")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Advanced Features")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("integration")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("true", "WeekdayTask", "7", null, DisplayName="Timer with condition-based routing(true,WeekdayTask,7)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("false", "SkipTask", "8", null, DisplayName="Timer with condition-based routing(false,SkipTask,8)")]
        public async global::System.Threading.Tasks.Task TimerWithCondition_BasedRouting(string triggered, string executedNode, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("triggered", triggered);
            argumentsOfScenario.Add("executedNode", executedNode);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Timer with condition-based routing", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 87
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 88
    await testRunner.GivenAsync("I have a Timer node \"CheckSchedule\" with cron expression \"0 9 * * 1-5\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 89
    await testRunner.AndAsync("\"CheckSchedule\" connects to \"WeekdayTask\" with condition \"GetInput(\'Triggered\') =" +
                        "= true\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 90
    await testRunner.AndAsync("\"CheckSchedule\" connects to \"SkipTask\" with condition \"GetInput(\'Triggered\') == f" +
                        "alse\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 91
    await testRunner.AndAsync("current time matches the schedule", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 92
    await testRunner.WhenAsync("I start the workflow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 93
    await testRunner.ThenAsync("\"CheckSchedule\" should evaluate the schedule", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 94
    await testRunner.AndAsync(string.Format("Triggered output should be {0}", triggered), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 95
    await testRunner.AndAsync(string.Format("{0} should execute", executedNode), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Nested container execution")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Nested container execution")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Advanced Features")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task NestedContainerExecution()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Nested container execution", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 103
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 104
    await testRunner.GivenAsync("I have an outer Container \"Outer\" with child Container \"Inner\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 105
    await testRunner.AndAsync("\"Inner\" has child nodes \"A\", \"B\", \"C\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 106
    await testRunner.AndAsync("\"Outer\" has additional child node \"D\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 107
    await testRunner.WhenAsync("I start the workflow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 108
    await testRunner.ThenAsync("\"Inner\" container should execute as a child of \"Outer\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 109
    await testRunner.AndAsync("\"A\", \"B\", \"C\" should execute within \"Inner\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 110
    await testRunner.AndAsync("\"Inner\" should complete when all its children complete", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 111
    await testRunner.AndAsync("\"D\" should execute in parallel with \"Inner\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 112
    await testRunner.AndAsync("\"Outer\" should complete when both \"Inner\" and \"D\" complete", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 113
    await testRunner.AndAsync("ChildResults should be aggregated at each container level", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Multi-level nested containers")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Multi-level nested containers")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Advanced Features")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task Multi_LevelNestedContainers()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Multi-level nested containers", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 116
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Level",
                            "Container",
                            "Children"});
                table3.AddRow(new string[] {
                            "1",
                            "Root",
                            "Level2A, Level2B"});
                table3.AddRow(new string[] {
                            "2",
                            "Level2A",
                            "Level3A"});
                table3.AddRow(new string[] {
                            "3",
                            "Level3A",
                            "Level4A, Level4B"});
                table3.AddRow(new string[] {
                            "4",
                            "Level4A",
                            "TaskA, TaskB, TaskC"});
#line 117
    await testRunner.GivenAsync("I have containers nested 4 levels deep:", ((string)(null)), table3, "Given ");
#line hidden
#line 123
    await testRunner.WhenAsync("I start the workflow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 124
    await testRunner.ThenAsync("all levels should execute correctly", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 125
    await testRunner.AndAsync("completion should propagate from innermost to outermost", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 126
    await testRunner.AndAsync("Root ChildResults should contain aggregated data from all levels", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 127
    await testRunner.AndAsync("the workflow should complete successfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Dynamic workflow modification - add node at runtime")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Dynamic workflow modification - add node at runtime")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Advanced Features")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task DynamicWorkflowModification_AddNodeAtRuntime()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Dynamic workflow modification - add node at runtime", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 130
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 131
    await testRunner.GivenAsync("I have a running workflow", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 132
    await testRunner.AndAsync("the workflow is currently executing node \"NodeB\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 133
    await testRunner.WhenAsync("I dynamically add a new node \"NodeX\" with connections", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 134
    await testRunner.AndAsync("I connect \"NodeB\" to \"NodeX\" on Complete", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 135
    await testRunner.ThenAsync("\"NodeX\" should be added to the workflow graph", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 136
    await testRunner.AndAsync("when \"NodeB\" completes, \"NodeX\" should execute", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 137
    await testRunner.AndAsync("the workflow should complete successfully with the new node", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Dynamic workflow modification - disable connection")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Dynamic workflow modification - disable connection")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Advanced Features")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task DynamicWorkflowModification_DisableConnection()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Dynamic workflow modification - disable connection", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 140
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 141
    await testRunner.GivenAsync("I have a workflow with nodes \"Source\", \"Target1\", \"Target2\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 142
    await testRunner.AndAsync("\"Source\" connects to both \"Target1\" and \"Target2\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 143
    await testRunner.AndAsync("the workflow is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 144
    await testRunner.WhenAsync("I disable the connection from \"Source\" to \"Target1\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 145
    await testRunner.AndAsync("\"Source\" completes", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 146
    await testRunner.ThenAsync("only \"Target2\" should execute", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 147
    await testRunner.AndAsync("\"Target1\" should not execute", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 148
    await testRunner.AndAsync("message should not be routed to \"Target1\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Dynamic workflow modification - enable disabled connection")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Dynamic workflow modification - enable disabled connection")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Advanced Features")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task DynamicWorkflowModification_EnableDisabledConnection()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Dynamic workflow modification - enable disabled connection", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 151
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 152
    await testRunner.GivenAsync("I have a workflow with a disabled connection \"A\" → \"B\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 153
    await testRunner.AndAsync("the connection is initially IsEnabled = false", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 154
    await testRunner.WhenAsync("I enable the connection at runtime", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 155
    await testRunner.AndAsync("node \"A\" completes", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 156
    await testRunner.ThenAsync("the message should be routed to \"B\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 157
    await testRunner.AndAsync("\"B\" should execute", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 158
    await testRunner.AndAsync("the workflow should complete successfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Checkpoint workflow state")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Checkpoint workflow state")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Advanced Features")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task CheckpointWorkflowState()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Checkpoint workflow state", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 161
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 162
    await testRunner.GivenAsync("I have a long-running workflow with 10 nodes", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 163
    await testRunner.AndAsync("checkpointing is enabled", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 164
    await testRunner.WhenAsync("the workflow executes through 5 nodes", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 165
    await testRunner.AndAsync("I create a checkpoint", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 166
    await testRunner.ThenAsync("the checkpoint should capture current workflow state", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 167
    await testRunner.AndAsync("the checkpoint should include completed node states", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 168
    await testRunner.AndAsync("the checkpoint should include workflow variables", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 169
    await testRunner.AndAsync("the checkpoint should include pending message queues", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Resume workflow from checkpoint")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Resume workflow from checkpoint")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Advanced Features")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task ResumeWorkflowFromCheckpoint()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Resume workflow from checkpoint", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 172
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 173
    await testRunner.GivenAsync("I have a checkpointed workflow that failed at node \"Step5\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 174
    await testRunner.AndAsync("nodes \"Step1\" through \"Step4\" completed successfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 175
    await testRunner.WhenAsync("I resume the workflow from the checkpoint", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 176
    await testRunner.ThenAsync("nodes \"Step1\" through \"Step4\" should not re-execute", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 177
    await testRunner.AndAsync("execution should resume at \"Step5\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 178
    await testRunner.AndAsync("workflow variables should be restored from checkpoint", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 179
    await testRunner.AndAsync("the workflow should complete if \"Step5\" succeeds", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Checkpoint and resume with modified workflow")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Checkpoint and resume with modified workflow")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Advanced Features")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task CheckpointAndResumeWithModifiedWorkflow()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "16";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Checkpoint and resume with modified workflow", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 182
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 183
    await testRunner.GivenAsync("I have a checkpointed workflow", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 184
    await testRunner.AndAsync("I modify the workflow definition after checkpoint", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 185
    await testRunner.WhenAsync("I resume from the checkpoint", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 186
    await testRunner.ThenAsync("the engine should detect the modification", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 187
    await testRunner.AndAsync("appropriate validation should occur", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 188
    await testRunner.AndAsync("the engine should handle compatibility issues", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 189
    await testRunner.AndAsync("resume should succeed if modifications are compatible", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Resume failed workflow with error correction")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Resume failed workflow with error correction")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Advanced Features")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("integration")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("errorhandling")]
        public async global::System.Threading.Tasks.Task ResumeFailedWorkflowWithErrorCorrection()
        {
            string[] tagsOfScenario = new string[] {
                    "integration",
                    "errorhandling"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "17";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Resume failed workflow with error correction", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 192
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 193
    await testRunner.GivenAsync("I have a workflow that failed at node \"FailingNode\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 194
    await testRunner.AndAsync("I create a checkpoint before the failure", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 195
    await testRunner.AndAsync("I fix the issue causing the failure", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 196
    await testRunner.WhenAsync("I resume from checkpoint", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 197
    await testRunner.ThenAsync("\"FailingNode\" should execute again", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 198
    await testRunner.AndAsync("this time it should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 199
    await testRunner.AndAsync("the workflow should continue from that point", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 200
    await testRunner.AndAsync("the workflow should complete successfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Automatic checkpointing at intervals")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Automatic checkpointing at intervals")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Advanced Features")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task AutomaticCheckpointingAtIntervals()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "18";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Automatic checkpointing at intervals", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 203
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 204
    await testRunner.GivenAsync("I have a long-running workflow with auto-checkpoint enabled", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 205
    await testRunner.AndAsync("checkpoint interval is set to every 5 nodes", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 206
    await testRunner.WhenAsync("I start the workflow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 207
    await testRunner.ThenAsync("checkpoints should be created after nodes 5, 10, 15, etc.", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 208
    await testRunner.AndAsync("each checkpoint should contain current state", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 209
    await testRunner.AndAsync("checkpoints should not significantly impact performance", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 210
    await testRunner.AndAsync("the workflow should complete successfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Subflow with container children")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Subflow with container children")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Advanced Features")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task SubflowWithContainerChildren()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "19";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Subflow with container children", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 213
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 214
    await testRunner.GivenAsync("I have a Subflow node that loads a workflow containing Containers", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 215
    await testRunner.AndAsync("the subflow\'s workflow has nested containers", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 216
    await testRunner.WhenAsync("I execute the subflow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 217
    await testRunner.ThenAsync("the external workflow should load correctly", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 218
    await testRunner.AndAsync("containers within the subflow should execute", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 219
    await testRunner.AndAsync("container children should execute correctly", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 220
    await testRunner.AndAsync("the subflow should aggregate all results", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 221
    await testRunner.AndAsync("control should return to parent workflow", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Complex workflow with all advanced features")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Complex workflow with all advanced features")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Advanced Features")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("integration")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("slow")]
        public async global::System.Threading.Tasks.Task ComplexWorkflowWithAllAdvancedFeatures()
        {
            string[] tagsOfScenario = new string[] {
                    "integration",
                    "slow"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "20";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Complex workflow with all advanced features", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 224
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Feature",
                            "Description"});
                table4.AddRow(new string[] {
                            "Containers",
                            "3 container nodes with children"});
                table4.AddRow(new string[] {
                            "Subflows",
                            "2 subflow calls to external workflows"});
                table4.AddRow(new string[] {
                            "Timers",
                            "1 timer trigger node"});
                table4.AddRow(new string[] {
                            "Control Flow",
                            "IfElse, ForEach, Switch nodes"});
                table4.AddRow(new string[] {
                            "Error Handling",
                            "Retry policies and fallback nodes"});
                table4.AddRow(new string[] {
                            "Concurrency",
                            "Parallel execution with limits"});
#line 225
    await testRunner.GivenAsync("I have a workflow combining:", ((string)(null)), table4, "Given ");
#line hidden
#line 233
    await testRunner.WhenAsync("I start the workflow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 234
    await testRunner.ThenAsync("all features should work together correctly", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 235
    await testRunner.AndAsync("the workflow should execute to completion", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 236
    await testRunner.AndAsync("all nodes should behave as expected", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 237
    await testRunner.AndAsync("final state should reflect all operations", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 238
    await testRunner.AndAsync("the workflow should complete within 5 seconds", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
