// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace ExecutionEngine.IntegrationTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class ControlFlowFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Control Flow", "  As a workflow designer\r\n  I want to use conditional branching and loops\r\n  So t" +
                "hat I can create dynamic workflows", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "ControlFlow.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/ControlFlow.feature.ndjson", 22);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("If-Else conditional execution")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("If-Else conditional execution")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Control Flow")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("integration")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("smoke")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("10", "HighValueHandler", "TrueBranch", "true", "0", null, DisplayName="If-Else conditional execution(10,HighValueHandler,TrueBranch,true,0)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("3", "LowValueHandler", "FalseBranch", "false", "1", null, DisplayName="If-Else conditional execution(3,LowValueHandler,FalseBranch,false,1)")]
        public async global::System.Threading.Tasks.Task If_ElseConditionalExecution(string count, string executedNode, string branch, string result, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration",
                    "smoke"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("count", count);
            argumentsOfScenario.Add("executedNode", executedNode);
            argumentsOfScenario.Add("branch", branch);
            argumentsOfScenario.Add("result", result);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("If-Else conditional execution", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 7
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await testRunner.GivenAsync("I have an IfElse node \"CheckValue\" with condition \"GetGlobal(\'count\') > 5\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 9
    await testRunner.AndAsync("\"CheckValue\" connects to \"HighValueHandler\" via \"TrueBranch\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 10
    await testRunner.AndAsync("\"CheckValue\" connects to \"LowValueHandler\" via \"FalseBranch\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 11
    await testRunner.AndAsync(string.Format("workflow variable \"count\" is set to {0}", count), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 12
    await testRunner.WhenAsync("I start the workflow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 13
    await testRunner.ThenAsync(string.Format("only {0} should execute", executedNode), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 14
    await testRunner.AndAsync(string.Format("the node output should contain BranchTaken \"{0}\"", branch), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
    await testRunner.AndAsync(string.Format("the node output should contain ConditionResult {0}", result), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("If-Else with complex condition accessing multiple contexts")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("If-Else with complex condition accessing multiple contexts")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Control Flow")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("integration")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("21", "US", "true", "2", null, DisplayName="If-Else with complex condition accessing multiple contexts(21,US,true,2)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("17", "US", "false", "3", null, DisplayName="If-Else with complex condition accessing multiple contexts(17,US,false,3)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("21", "UK", "false", "4", null, DisplayName="If-Else with complex condition accessing multiple contexts(21,UK,false,4)")]
        public async global::System.Threading.Tasks.Task If_ElseWithComplexConditionAccessingMultipleContexts(string age, string country, string result, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("age", age);
            argumentsOfScenario.Add("country", country);
            argumentsOfScenario.Add("result", result);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("If-Else with complex condition accessing multiple contexts", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 23
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 24
    await testRunner.GivenAsync("I have an IfElse node with condition \"(int)GetInput(\'age\') >= 18 && GetGlobal(\'co" +
                        "untry\') == \'US\'\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 25
    await testRunner.AndAsync(string.Format("the node receives input \"age\" with value {0}", age), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 26
    await testRunner.AndAsync(string.Format("workflow variable \"country\" is set to \"{0}\"", country), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
    await testRunner.WhenAsync("the IfElse node executes", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 28
    await testRunner.ThenAsync(string.Format("the condition should evaluate to {0}", result), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("ForEach collection iteration")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ForEach collection iteration")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Control Flow")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("integration")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("smoke")]
        public async global::System.Threading.Tasks.Task ForEachCollectionIteration()
        {
            string[] tagsOfScenario = new string[] {
                    "integration",
                    "smoke"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("ForEach collection iteration", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 37
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 38
    await testRunner.GivenAsync("I have a ForEach node \"ProcessFiles\" with collection expression \"GetGlobal(\'files" +
                        "\')\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 39
    await testRunner.AndAsync("\"ProcessFiles\" connects to \"ProcessFile\" via \"LoopBody\" with trigger type \"Next\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
    await testRunner.AndAsync("workflow variable \"files\" contains [\"file1.txt\", \"file2.txt\", \"file3.txt\"]", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 41
    await testRunner.WhenAsync("I start the workflow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 42
    await testRunner.ThenAsync("\"ProcessFile\" should execute 3 times", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 43
    await testRunner.AndAsync("each iteration should receive a different file name", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 44
    await testRunner.AndAsync("each iteration should receive the correct index (0, 1, 2)", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 45
    await testRunner.AndAsync("the ForEach output should show ItemsProcessed = 3", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("ForEach with LINQ expression")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ForEach with LINQ expression")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Control Flow")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task ForEachWithLINQExpression()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("ForEach with LINQ expression", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 48
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 49
    await testRunner.GivenAsync("I have a ForEach node with collection expression \"GetGlobal(\'items\').Cast<int>()." +
                        "Where(x => x > 5)\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 50
    await testRunner.AndAsync("workflow variable \"items\" contains [1, 3, 6, 8, 10, 12]", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 51
    await testRunner.WhenAsync("I start the workflow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 52
    await testRunner.ThenAsync("the loop body should execute 4 times", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 53
    await testRunner.AndAsync("iterations should process values [6, 8, 10, 12]", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("While loop with condition re-evaluation")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("While loop with condition re-evaluation")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Control Flow")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("integration")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("smoke")]
        public async global::System.Threading.Tasks.Task WhileLoopWithConditionRe_Evaluation()
        {
            string[] tagsOfScenario = new string[] {
                    "integration",
                    "smoke"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("While loop with condition re-evaluation", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 56
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 57
    await testRunner.GivenAsync("I have a While node \"CounterLoop\" with condition \"GetGlobal(\'counter\') < 5\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 58
    await testRunner.AndAsync("\"CounterLoop\" connects to \"IncrementCounter\" via \"LoopBody\" with trigger type \"Ne" +
                        "xt\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 59
    await testRunner.AndAsync("\"IncrementCounter\" connects back to \"CounterLoop\" on Complete", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 60
    await testRunner.AndAsync("\"IncrementCounter\" increments workflow variable \"counter\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 61
    await testRunner.AndAsync("workflow variable \"counter\" is set to 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 62
    await testRunner.WhenAsync("I start the workflow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 63
    await testRunner.ThenAsync("the loop should execute 5 times", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 64
    await testRunner.AndAsync("the final value of \"counter\" should be 5", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
    await testRunner.AndAsync("the While output should show IterationCount = 5", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("While loop max iterations protection")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("While loop max iterations protection")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Control Flow")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task WhileLoopMaxIterationsProtection()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("While loop max iterations protection", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 68
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 69
    await testRunner.GivenAsync("I have a While node with condition \"true\" and MaxIterations 10", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 70
    await testRunner.WhenAsync("I start the workflow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 71
    await testRunner.ThenAsync("the loop should stop after 10 iterations", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 72
    await testRunner.AndAsync("the node should fail with \"infinite loop\" error", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 73
    await testRunner.AndAsync("the workflow should fail", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Switch multi-way branching")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Switch multi-way branching")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Control Flow")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("integration")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("smoke")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("success", "HandleSuccess", "success", "9", null, DisplayName="Switch multi-way branching(success,HandleSuccess,success,9)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("failure", "HandleFailure", "failure", "10", null, DisplayName="Switch multi-way branching(failure,HandleFailure,failure,10)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("unknown", "HandleDefault", "Default", "11", null, DisplayName="Switch multi-way branching(unknown,HandleDefault,Default,11)")]
        public async global::System.Threading.Tasks.Task SwitchMulti_WayBranching(string status, string executedNode, string matchedCase, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration",
                    "smoke"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("status", status);
            argumentsOfScenario.Add("executedNode", executedNode);
            argumentsOfScenario.Add("matchedCase", matchedCase);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Switch multi-way branching", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 76
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 77
    await testRunner.GivenAsync("I have a Switch node \"Router\" with expression \"(string)GetInput(\'status\')\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "caseValue",
                            "portName"});
                table6.AddRow(new string[] {
                            "success",
                            "SuccessPort"});
                table6.AddRow(new string[] {
                            "failure",
                            "FailurePort"});
                table6.AddRow(new string[] {
                            "pending",
                            "PendingPort"});
#line 78
    await testRunner.AndAsync("\"Router\" has cases:", ((string)(null)), table6, "And ");
#line hidden
#line 83
    await testRunner.AndAsync("\"Router\" connects to \"HandleSuccess\" via \"SuccessPort\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 84
    await testRunner.AndAsync("\"Router\" connects to \"HandleFailure\" via \"FailurePort\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 85
    await testRunner.AndAsync("\"Router\" connects to \"HandlePending\" via \"PendingPort\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 86
    await testRunner.AndAsync("\"Router\" connects to \"HandleDefault\" via \"Default\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 87
    await testRunner.WhenAsync(string.Format("the node receives input \"status\" with value \"{0}\"", status), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 88
    await testRunner.AndAsync("I start the workflow", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 89
    await testRunner.ThenAsync(string.Format("only {0} should execute", executedNode), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 90
    await testRunner.AndAsync(string.Format("the output should contain MatchedCase \"{0}\"", matchedCase), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Switch with expression evaluation")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Switch with expression evaluation")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Control Flow")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("integration")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("95", "A", "12", null, DisplayName="Switch with expression evaluation(95,A,12)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("75", "B", "13", null, DisplayName="Switch with expression evaluation(75,B,13)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("60", "C", "14", null, DisplayName="Switch with expression evaluation(60,C,14)")]
        public async global::System.Threading.Tasks.Task SwitchWithExpressionEvaluation(string score, string grade, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("score", score);
            argumentsOfScenario.Add("grade", grade);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Switch with expression evaluation", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 99
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 100
    await testRunner.GivenAsync("I have a Switch node with expression \"GetInput(\'score\') >= 90 ? \'A\' : GetInput(\'s" +
                        "core\') >= 70 ? \'B\' : \'C\'\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 101
    await testRunner.AndAsync(string.Format("the node receives input \"score\" with value {0}", score), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 102
    await testRunner.WhenAsync("the Switch node executes", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 103
    await testRunner.ThenAsync(string.Format("the expression should evaluate to \"{0}\"", grade), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 104
    await testRunner.AndAsync(string.Format("the matched case should be \"{0}\"", grade), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Nested loop iteration")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Nested loop iteration")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Control Flow")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("integration")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("slow")]
        public async global::System.Threading.Tasks.Task NestedLoopIteration()
        {
            string[] tagsOfScenario = new string[] {
                    "integration",
                    "slow"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Nested loop iteration", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 113
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 114
    await testRunner.GivenAsync("I have an outer ForEach node iterating over [1, 2, 3]", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 115
    await testRunner.AndAsync("an inner ForEach node iterating over [\"A\", \"B\"]", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 116
    await testRunner.WhenAsync("I start the workflow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 117
    await testRunner.ThenAsync("the total executions should be 6", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 118
    await testRunner.AndAsync("I should see combinations [(1,A), (1,B), (2,A), (2,B), (3,A), (3,B)]", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("While loop with external variable modification")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("While loop with external variable modification")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Control Flow")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task WhileLoopWithExternalVariableModification()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "16";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("While loop with external variable modification", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 121
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 122
    await testRunner.GivenAsync("I have a While node with condition \"GetGlobal(\'flag\') == true\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 123
    await testRunner.AndAsync("a loop body that sets \"flag\" to false after 3 iterations", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 124
    await testRunner.WhenAsync("I start the workflow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 125
    await testRunner.ThenAsync("the loop should execute exactly 3 times", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 126
    await testRunner.AndAsync("the loop should terminate when flag becomes false", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("ForEach with empty collection")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ForEach with empty collection")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Control Flow")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("integration")]
        public async global::System.Threading.Tasks.Task ForEachWithEmptyCollection()
        {
            string[] tagsOfScenario = new string[] {
                    "integration"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "17";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("ForEach with empty collection", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 129
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 130
    await testRunner.GivenAsync("I have a ForEach node with an empty collection", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 131
    await testRunner.WhenAsync("I start the workflow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 132
    await testRunner.ThenAsync("the loop body should not execute", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 133
    await testRunner.AndAsync("the ForEach should complete successfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 134
    await testRunner.AndAsync("ItemsProcessed should be 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Branch convergence after If-Else")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Branch convergence after If-Else")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Control Flow")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("integration")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("true", "TrueBranch", "18", null, DisplayName="Branch convergence after If-Else(true,TrueBranch,18)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("false", "FalseBranch", "19", null, DisplayName="Branch convergence after If-Else(false,FalseBranch,19)")]
        public async global::System.Threading.Tasks.Task BranchConvergenceAfterIf_Else(string condition, string executedBranch, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "integration"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("condition", condition);
            argumentsOfScenario.Add("executedBranch", executedBranch);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Branch convergence after If-Else", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 137
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 138
    await testRunner.GivenAsync("I have an IfElse node with True and False branches", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 139
    await testRunner.AndAsync("both branches connect to a common \"Join\" node", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 140
    await testRunner.WhenAsync(string.Format("I start the workflow with condition = {0}", condition), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 141
    await testRunner.ThenAsync(string.Format("the \"{0}\" branch should execute", executedBranch), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 142
    await testRunner.AndAsync("the \"Join\" node should execute after the branch", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 143
    await testRunner.AndAsync("the workflow should complete successfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
